<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xsi:schemaLocation="
http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.0.xsd
http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop-2.0.xsd">

    <!--
        Integration test for error handling
        TODO move it to error package catalogue?
    -->

    <aop:config>
        <aop:aspect ref="error.advice">
            <aop:after-throwing
                    pointcut="execution(* no.stelvio.common.error.TestThrower.throw*(..))"
                    throwing="throwable" 
                    method="afterThrowing"/>
        </aop:aspect>
    </aop:config>

    <!-- This makes ErrorHandlingFacade an error handler for every bean this advice is injected onto  -->
    <bean id="error.advice" class="no.stelvio.common.error.support.ExceptionHandlingAdvice">
        <property name="exceptionHandlerFacade" ref="error.facade"/>
    </bean>

    
    <bean id="error.facade" class="no.stelvio.common.error.support.DefaultExceptionHandlerFacade">
        <property name="defaultStrategy" ref="error.strategy"/>
    </bean>
    <bean id="error.strategy" class="no.stelvio.common.error.strategy.support.ExceptionHandlerStrategyChain">
        <property name="strategies">
            <set>
                <ref local="error.logStrategy"/>
                <ref local="error.rethrowStrategy"/>
            </set>
        </property>
    </bean>
    <bean id="error.logStrategy" class="no.stelvio.common.error.strategy.support.LoggerExceptionHandlerStrategy">
        <property name="errorDefinitionResolver" ref="error.errorResolverFb"/>
    </bean>
    <bean id="error.rethrowStrategy" class="no.stelvio.common.error.strategy.support.MorpherExceptionHandlerStrategy"/>


    <bean id="error.errorResolverFb" class="no.stelvio.common.error.resolver.support.ErrorDefinitionResolverFactoryBean">
        <property name="errorDefinitionRetriever" ref="error.retriever"/>
    </bean>
    <bean id="error.retriever" class="no.stelvio.common.error.retriever.TestErrorDefinitionRetriever"/>

    
    <bean id="error.testThrower" class="no.stelvio.common.error.TestThrower"/>
    <bean id="error.testCatcher" class="no.stelvio.common.error.TestCatcher">
        <property name="testThrower" ref="error.testThrower"/>
    </bean>
</beans>

